services:
  - type: web
    name: django-blog
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_site.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.0"
    autoDeploy: true

databases:
  - name: django-blog-db
    databaseName: django_blog
    user: django_blog_user
    plan: free
    region: oregon
